global:
  save_path: ./output_hy3_zero3

model:
  name: HYV3MoE
  model_path: tencent/Hy3-preview
  trust_remote_code: true
  torch_dtype: auto
  device_map: None
  low_cpu_mem_usage: true
  use_cache: false

compression:
  name: QAT
  quantization:
    name: fp8_static
    bits: 8
    quant_method:
      weight: per-tensor
      activation: per-tensor
    ignore_layers: ["lm_head", "embed_tokens", "gate.weight"]
  QAT:
    hf_dataset: null
    from_ptq_ckpt: ./output_ptq_hy3/hunyuanv3_a20b_fp8_static
    training_mode: end2end
    dist_mode: hf
    save_format: real
    do_train: true
    loss_type: cakld
    loss_topk: null
    kd_temperature: 1.0
    kd_alpha: 0.5
    lm_loss_weight: 1.0
    kd_loss_weight: 1.0
    plugin_config:
      enable_scale: true
      quant_config:
        use_weight_quant: true
        use_activation_quant: true
        use_qkv_quant: false
        weight_scale_init_value: 0.1
        activation_scale_init_value: 0.1
        learnable:
          act_scale: false
          weight_scale: true
          kv_scale: false
          norm: false
          lwc: false
    hf_args:
      bf16: true
      logging_steps: 1
      logging_first_step: true
      per_device_train_batch_size: 1
      gradient_accumulation_steps: 1
      learning_rate: 1.0e-6
      lr_scheduler_type: cosine
      num_train_epochs: 1
      max_steps: 3
      save_strategy: "no"
      warmup_ratio: 0.0
      max_grad_norm: 1.0
      gradient_checkpointing: true
      gradient_checkpointing_kwargs:
        use_reentrant: true
      deepspeed: configs/hunyuan/qat/fp8_static/learn_scale/ds_config_zero3.json

dataset:
  name: TextDataset
  data_path: ./dataset/sharegpt_gpt4/sharegpt_gpt4_256.jsonl
  max_seq_length: 2048
  num_samples: 256
  batch_size: 1
