global:
  save_path: ./output

model:
  name: HYV3MoE
  model_path: /apdcephfs_zwfy2/share_301053287/brunosu/all_models/hy3_0_a3b
  trust_remote_code: true
  torch_dtype: bfloat16
  device_map: auto
  low_cpu_mem_usage: true
  use_cache: false
  attn_implementation: eager

compression:
  name: PTQ
  quantization:
    name: fp8_static
    bits: 8
    quant_method:
      weight: per-tensor
      activation: per-tensor
    ignore_layers:
      - lm_head
      - embed_tokens
      - router.gate

dataset:
  name: TextDataset
  data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
  max_seq_length: 2048
  num_samples: 64
  batch_size: 1
